BackgroundEstimator Analysis Parameter Class
CNERG/RadClass pull request #14
Opened 2021-06-09 21:06 UTC by stompsjo

This introduces an analysis parameter class that plugs into `RadClass`: `BackgroundEstimator`. This small class processes gross count rates for each integrated time interval and sorts the set in ascending order of gross count rate magnitude. It then saves to a `.csv` file a percentage of the smallest count rates with corresponding timestamps.

A few notes:
- I have two "less-than-ideal" ways of writing the results to file. One way uses the class destructor `__del__` to write to file. This way, the file always is written at the end of an analysis script even if the script crashes. This does, however, require the class to be destructed if it is to be written and analyzed in the _same_ script (something I noticed when trying to write a test case). The alternative is to create a `write()` method which _must_ be called manually by a user script in order to be reviewed later. Which is better or should both be left in?
- The method `save_all` currently does not work but should be considered. The idea would be to save the timestamps and the _spectra_ rather than the gross count rate. This way, the smallest (in gross count rate terms) spectra could be reviewed in post-analysis.

2021-07-02 18:27 UTC, stompsjo commented
Did I accidentally rebase incorrectly? There are some files that are listed as "changed" in this PR but `main` already has those changes adopted...

2021-07-09 13:55 UTC, gonuke commented
There is definitely something tangled in the commit history, but it may not matter...

2021-07-09 13:59 UTC, gonuke commented
It probably is only an issue because it makes review harder.  We can discuss how to fix this perhaps...

2021-09-24 11:16 UTC, gonuke reviewed
I think we should discuss this. I'm not sure I can fully understand what's going on here....

2021-09-24 11:16 UTC, gonuke commented on RadClass/BackgroundEstimator.py
> +            self.store_all = store_all
Redundant with line 32

2021-10-06 14:11 UTC, stompsjo commented
I have tried to clean up `BackgroundEstimator` per our discussion. Many of the problems with this class were the result of me being on the fence about design questions. (`store_all`? `__del__`?) I have committed to a few design features that should be clear now and align with the framework for other classes in `RadClass`:

- `BackgroundEstimator` no longer has a `store_all` method and therefore no longer stores spectral information from `RadClass`. I think storing spectral information (primarily for writing to file) should be the responsibility of `RadClass` rather than any AnalysisParameter classes. I think this is also the case for `H0`. If a user wishes to pull spectral information from file, they can either store everything via `RadClass` or create a script using `DataSet.data_slice()` to gather specific rows.
- I removed the commented out `__del__` method. If a user wishes to write results to file, they will have to call `BackgroundEstimator.write()`, just like in `H0`. Or, a user could call `BackgroundEstimator.estimate()` and then review the class attributes directly, which store results.

2021-10-09 13:26 UTC, gonuke requested changes
You might want to consider how you could use `numpy.percentile()` and fancy indexing of your array to accomplish your estimate concisely and without pandas 

This is not syntactically correct, but conceptually....
```
val_at_confidence = numbly.percentile(data, confidence*100, axis=1)

return data[:,data < val_at_confidence]
```

2021-10-11 17:56 UTC, stompsjo commented
> You might want to consider how you could use `numpy.percentile()`

I have implemented this in `BackgroundEstimator.estimate()`. I apply the percentile filtering on the numpy data array and then save it to the Pandas DataFrame (`background`) for writing later.

2021-10-12 01:47 UTC, gonuke requested changes
Maybe we can ditch pandas here, after all?

2021-10-12 01:47 UTC, gonuke commented on RadClass/BackgroundEstimator.py
> +    background = pd.DataFrame(columns=['timestamp', 'count_rate'])
Now you really are only using this for CSV export.  What about `np.savetxt()`?

2021-10-12 16:43 UTC, stompsjo commented on RadClass/BackgroundEstimator.py
> +    background = pd.DataFrame(columns=['timestamp', 'count_rate'])
The only caveat is that I would not be able to include "table" headers like timestamp and count_rate, since `np.savetxt()` and `numpy` more generally requires the array to all be the same type. (At least this is what I encountered last time I tried.)

Maybe that is tolerable? Results don't necessarily need to be saved with labels if that is properly documented? Thoughts? Otherwise I agree that Pandas is unnecessary so far, since it is only used for CSV export _thoughout all_ of `RadClass`.

2021-10-26 17:17 UTC, gonuke approved these changes
LGTM - thanks @stompsjo

2021-10-26 17:17 UTC, merged